language: java
os: linux
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

cache:
  directories:
    - $HOME/.ivy2

before_install:
  - sudo apt-get update
  - sudo apt-get install ivy -y
  - sudo ln -s -T /usr/share/java/ivy.jar /usr/share/ant/lib/ivy*.jar

install:
  - ant ivy-bootstrap

script:
  - ant test
  - ant train -Dalgo=franknet -Dopt.ite=10
  - ant train -Dalgo=lambdarank -Dopt.ite=10
  - ant train -Dalgo=listnet -Dopt.ite=10
  - ant train -Dalgo=nnrank -Dopt.ite=10
  - ant train -Dalgo=oap -Dopt.ite=10
  - ant train -Dalgo=prank -Dopt.ite=10
  - ant train -Dalgo=ranknet -Dopt.ite=10
  - ant train -Dalgo=sortnet -Dopt.ite=10
